### ISSUE TITLE
[Crash] Using Tipped arrows with potioned bow crashes game

### ISSUE THREAD

**Issue by Akitori** [Cookiehook/Minecraft-Liquid-Enchanting#27]
As title says, i used vulnerability 2 (potion core potion) with a tipped arrow (any type sadly) and crashed the game. Various times.

**Comment by Cookiehook** [comment]
Dammit.That'll take priority over any functional changes once I've confirmed it. I'll get to it Friday or earlier.Can you give screenshots of what you're using? Specifically the bow and arrow tooltips. Also a list of mods you're using would be helpful, as there may be a third party interfering and causing the crash.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Akitori <notifications@github.com> Date: 07/04/2020  18:23  (GMT+00:00) To: Cookiehook/Minecraft-Liquid-Enchanting <Minecraft-Liquid-Enchanting@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Cookiehook/Minecraft-Liquid-Enchanting] [Crash] Using Tipped arrows with potioned bow crashes game (#27) 
As title says, i used vulnerability 2 (potion core potion) with a tipped arrow (any type sadly) and crashed the game. Various times.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Cookiehook/Minecraft-Liquid-Enchanting/issues/27",
"url": "https://github.com/Cookiehook/Minecraft-Liquid-Enchanting/issues/27",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Akitori** [comment]
Nevermind, testing resulted in me finding out this was more related to the actual curse arrow (random negative effect) than the actual potioned bows. This is why you should retest a hundred times, closing this. Sorry!
